DROP TRIGGER IF EXISTS AdvokatuSkaiciusBylai ON mido9017.Advokatai;
DROP TRIGGER IF EXISTS PosedzioData ON mido9017.Posedis;
DROP TRIGGER IF EXISTS BylosPradziosData ON mido9017.Byla;

DROP FUNCTION IF EXISTS AdvokatuSkaiciusBylai;
DROP FUNCTION IF EXISTS PosedzioData;
DROP FUNCTION IF EXISTS BylosPradziosData;

DROP MATERIALIZED VIEW IF EXISTS mido9017.MatView_Teisiamuju_Advokatu_Statistika;

DROP VIEW IF EXISTS mido9017.View_Teisiamuju_Su_Byla;
DROP VIEW IF EXISTS mido9017.View_Advokatu_Su_Byla;

DROP INDEX IF EXISTS mido9017.idx_TeisiamojoTel_Nr;
DROP INDEX IF EXISTS mido9017.idx_AdvokatoTel_Nr;
DROP INDEX IF EXISTS mido9017.idx_PosedzioLaikas;

ALTER TABLE mido9017.Posedis DROP CONSTRAINT IF EXISTS Byla CASCADE;
ALTER TABLE mido9017.Posedis DROP CONSTRAINT IF EXISTS Sale CASCADE;
ALTER TABLE mido9017.Advokatai DROP CONSTRAINT IF EXISTS Advokatas CASCADE;
ALTER TABLE mido9017.Advokatai DROP CONSTRAINT IF EXISTS Byla CASCADE;
ALTER TABLE mido9017.Teisiamieji DROP CONSTRAINT IF EXISTS Teisiamasis CASCADE;
ALTER TABLE mido9017.Teisiamieji DROP CONSTRAINT IF EXISTS Byla CASCADE;

DROP TABLE IF EXISTS mido9017.Teisiamasis;
DROP TABLE IF EXISTS mido9017.Teisiamieji;
DROP TABLE IF EXISTS mido9017.Advokatas;
DROP TABLE IF EXISTS mido9017.Advokatai;
DROP TABLE IF EXISTS mido9017.Byla;
DROP TABLE IF EXISTS mido9017.Posedis;
DROP TABLE IF EXISTS mido9017.Sale;
